### ISSUE TITLE
UBY: pydatalog site CSS: td { border-color: #cecece; }

### ISSUE THREAD

**Issue by westurner** [pcarbonn/pyDatalog#15]
The "Core Technology in pyDatalog" ``<table>`` is outstanding.
( https://sites.google.com/site/pydatalog/home )

This CSS rule makes it far easier to read, IMHO:

```css
div#sites-canvas-main-content td {
  border-color: #cecece;
}
```

* UBY: usability ( https://westurner.org/wiki/workflow#code-labels )
